//
//  DPCApp.h
//  DapiConnect
//
//  Created by Mohammed Ennabah on 3/3/20.
//  Copyright © 2020 Dapi. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "DPCConfigurations.h"
#import "DPCConnectionDetails.h"
#import "DPCClient.h"
NS_ASSUME_NONNULL_BEGIN

NS_SWIFT_NAME(DapiApp)
@interface DPCApp : NSObject

/*!
 @discussion Each connection to a bank account is associated with userID (generated by Dapi). You can retrieve all `userID`s that are associated to your user's clientUserID.
*/
@property (nonatomic, readonly, class) NSArray<NSString *> *userIDs;

- (instancetype)init __attribute__((unavailable("use shared property")));

/*!
 @discussion Returns info associated with a userID.
 For instance, details will include bankID and name.
 
 @param userID you can retrieve all available userIDs from `[DPCApp ]`.
*/
+ (DPCConnectionDetails *)connectionDetailsWithUserID:(NSString *)userID;

@end

NS_ASSUME_NONNULL_END
